//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.42
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitleAttribute("CapeOpenReactor")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Reactor Unit .Net")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("")]
[assembly: System.Reflection.AssemblyCompanyAttribute("Mose")]
[assembly: System.Reflection.AssemblyProductAttribute("")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("(C) 2005-2007 Mose")]
[assembly: System.Reflection.AssemblyTrademarkAttribute("")]
[assembly: System.Reflection.AssemblyCultureAttribute("")]
[assembly: System.Runtime.InteropServices.GuidAttribute("7ede14cb-6266-4148-9b33-049bb9abe3b2")]
[assembly: System.Runtime.InteropServices.ComVisibleAttribute(true)]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: Mose.CapeOpenToolkit.UnitProxy.CapeOpenUnitInfoAttribute(Mose.CapeOpenToolkit.UnitProxy.CapeOpenUnitInfoEnum.About, "UnitLibrary1")]
[assembly: Mose.CapeOpenToolkit.UnitProxy.CapeOpenUnitInfoAttribute(Mose.CapeOpenToolkit.UnitProxy.CapeOpenUnitInfoEnum.CapeVersion, "0.9-3")]
[assembly: Mose.CapeOpenToolkit.UnitProxy.CapeOpenUnitInfoAttribute(Mose.CapeOpenToolkit.UnitProxy.CapeOpenUnitInfoEnum.Description, "Reactor Unit .Net")]
[assembly: Mose.CapeOpenToolkit.UnitProxy.CapeOpenUnitInfoAttribute(Mose.CapeOpenToolkit.UnitProxy.CapeOpenUnitInfoEnum.Name, "ReactorUnit")]
[assembly: Mose.CapeOpenToolkit.UnitProxy.CapeOpenUnitInfoAttribute(Mose.CapeOpenToolkit.UnitProxy.CapeOpenUnitInfoEnum.Help, "http://tempuri.org/UnitLibrary1/Unit1")]
[assembly: Mose.CapeOpenToolkit.UnitProxy.CapeOpenUnitInfoAttribute(Mose.CapeOpenToolkit.UnitProxy.CapeOpenUnitInfoEnum.VendorURL, "http://tempuri.org/")]

